# Generated by Django 3.2.6 on 2021-08-29 07:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('spam_score', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Spam',
        ),
    ]
