# Generated by Django 3.2.6 on 2021-08-29 07:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210829_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaluser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
