# Generated by Django 3.2.6 on 2021-08-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_globaluser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaluser',
            name='phone',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
